[global_tags]
  environment = "smart_home"
  location = "khimki"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "grafana-token-123"
  organization = "smart_home"
  bucket = "sensors"

[[inputs.cpu]]
  percpu = true
  totalcpu = true

[[inputs.mem]]
  # total, available, used, free

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.net]]

[[inputs.system]]

[[inputs.processes]]

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  container_names = []
  timeout = "5s"
  perdevice = true
  total = true
  taginclude = ["io_service_bytes_recursive", "io_service_time_recursive"]
